echo "--- Executing initialization force file for ../testcode/mp1factorial.asm ---"

echo "Resetting processor for 5 ns."
force /reset_l 0 @0
force /reset_l 1 @5

echo "Done initializing processor, loading ../testcode/mp1factorial.asm program code."
run 5
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(0) X"3F"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(1) X"98"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(2) X"3F"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(3) X"92"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(4) X"41"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(5) X"12"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(6) X"41"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(7) X"14"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(8) X"42"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(9) X"12"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(10) X"7F"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(11) X"92"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(12) X"44"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(13) X"14"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(14) X"82"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(15) X"56"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(16) X"40"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(17) X"10"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(18) X"84"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(19) X"14"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(20) X"FD"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(21) X"03"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(22) X"C4"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(23) X"16"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(24) X"04"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(25) X"0C"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(26) X"C3"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(27) X"54"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(28) X"00"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(29) X"52"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(30) X"3F"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(31) X"91"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(32) X"F7"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(33) X"0F"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(34) X"FF"
change mp3_cpu/PipeMem/DRAM_MP3/vhdl_memory/mem(35) X"0F"
run 5
echo "Done loading ../testcode/mp1factorial.asm program code."
