-- VHDL Entity ece411.BWdelay.generatedInstance
--
-- Created:
--          by - baker30.ews (gelib-057-20.ews.illinois.edu)
--          at - 20:23:33 02/24/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;
USE ieee.std_logic_arith.all;

ENTITY BWdelay IS
   PORT( 
      BitWrite : OUT    std_logic;
      F5       : IN     std_logic
   );

END BWdelay ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF BWdelay IS 
BEGIN


END generatedInstance;
