-- VHDL Entity ece411.DetermDW.symbol
--
-- Created:
--          by - lachman1.ews (evrt-252-38.ews.illinois.edu)
--          at - 16:37:26 04/18/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY DetermDW IS
   PORT( 
      CacheWrite : IN     std_logic;
      HITx       : IN     std_logic;
      Hit        : IN     std_logic;
      LRUx       : IN     std_logic;
      Miss       : IN     STD_LOGIC;
      DataWriteX : OUT    std_logic
   );

-- Declarations

END DetermDW ;

--
-- VHDL Architecture ece411.DetermDW.struct
--
-- Created:
--          by - lachman1.ews (evrt-252-38.ews.illinois.edu)
--          at - 16:37:26 04/18/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF DetermDW IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F  : STD_LOGIC;
   SIGNAL F1 : STD_LOGIC;


   -- Component Declarations
   COMPONENT AND3
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      C : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT OR2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND3 USE ENTITY mp3lib.AND3;
   FOR ALL : OR2 USE ENTITY mp3lib.OR2;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_2 : AND3
      PORT MAP (
         A => Hit,
         B => HITx,
         C => CacheWrite,
         F => F
      );
   U_3 : AND3
      PORT MAP (
         A => LRUx,
         B => Miss,
         C => CacheWrite,
         F => F1
      );
   U_0 : OR2
      PORT MAP (
         A => F,
         B => F1,
         F => DataWriteX
      );

END struct;
