-- VHDL Entity ece411.EX_StripControls.generatedInstance
--
-- Created:
--          by - baker30.ews (gelib-057-15.ews.illinois.edu)
--          at - 03:11:57 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY EX_StripControls IS
   PORT( 
      ALUMUXSel      : OUT    LC3B_4MUXSEL;
      aluop          : OUT    LC3B_ALUOP;
      CLK            : IN     STD_LOGIC;
      ex_controls_in : IN     CONTROL_WORD;
      LoadNZP        : OUT    std_logic
   );

END EX_StripControls ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF EX_StripControls IS 
BEGIN


END generatedInstance;
