-- VHDL Entity ece411.ICache.interface
--
-- Created:
--          by - lachman1.ews (siebl-0220-04.ews.illinois.edu)
--          at - 03:18:15 04/26/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ICache IS
   PORT( 
      CLK          : IN     STD_LOGIC;
      I_ADDRESS    : IN     LC3B_WORD;
      I_MREAD_L    : IN     STD_LOGIC;
      I_PMDATAIN   : IN     LC3B_OWORD;
      I_PMRESP_H   : IN     STD_LOGIC;
      RESET_L      : IN     STD_LOGIC;
      I_ADDRESS_pm : OUT    LC3B_WORD;
      I_DATAIN     : OUT    LC3B_WORD;
      I_MREAD_pm_L : OUT    STD_LOGIC;
      I_MRESP_H    : OUT    STD_LOGIC
   );

-- Declarations

END ICache ;

--
-- VHDL Architecture ece411.ICache.struct
--
-- Created:
--          by - lachman1.ews (siebl-0220-04.ews.illinois.edu)
--          at - 03:18:15 04/26/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF ICache IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL CacheWrite : std_logic;
   SIGNAL DirtyOut   : std_logic;
   SIGNAL Evict_H    : std_logic;
   SIGNAL IMissCount : LC3B_Word;
   SIGNAL IMissPlus1 : LC3B_Word;
   SIGNAL MissCount  : std_logic;
   SIGNAL WRITE_L    : std_logic;
   SIGNAL dout       : std_logic;
   SIGNAL hit        : std_logic;


   -- Component Declarations
   COMPONENT Cache_Controller
   PORT (
      DirtyOut   : IN     std_logic ;
      MREAD_L    : IN     std_logic ;
      MWRITEL_L  : IN     std_logic ;
      PMRESP_H   : IN     STD_LOGIC ;
      RESET_L    : IN     std_logic ;
      clk        : IN     std_logic ;
      hit        : IN     std_logic ;
      CacheWrite : OUT    std_logic ;
      Evict_H    : OUT    std_logic ;
      MissCount  : OUT    std_logic ;
      PMREAD_L   : OUT    STD_LOGIC ;
      PMWRITE_L  : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT Cache_Datapath
   PORT (
      ADDRESS    : IN     LC3b_word ;
      CacheWrite : IN     std_logic ;
      DATAOUT    : IN     LC3b_word ;
      Evict_H    : IN     std_logic ;
      MREAD_L    : IN     std_logic ;
      MWRITEH_L  : IN     std_logic ;
      MWRITEL_L  : IN     std_logic ;
      PMDATAIN   : IN     LC3B_OWORD ;
      RESET_L    : IN     std_logic ;
      clk        : IN     std_logic ;
      DATAIN     : OUT    LC3b_word ;
      DirtyOut   : OUT    std_logic ;
      LRUOut     : OUT    std_logic ;
      MRESP_H    : OUT    std_logic ;
      PMADDRESS  : OUT    LC3B_WORD ;
      PMDATAOUT  : OUT    LC3B_OWORD ;
      hit        : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Plus1
   PORT (
      CLK     : IN     STD_LOGIC;
      DataIn  : IN     LC3B_Word;
      DataOut : OUT    LC3B_Word
   );
   END COMPONENT;
   COMPONENT Reg16
   PORT (
      Input  : IN     LC3b_word ;
      RESET  : IN     std_logic ;
      clk    : IN     std_logic ;
      load   : IN     std_logic ;
      Output : OUT    LC3b_word 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Cache_Controller USE ENTITY ece411.Cache_Controller;
   FOR ALL : Cache_Datapath USE ENTITY ece411.Cache_Datapath;
   FOR ALL : Plus1 USE ENTITY ece411.Plus1;
   FOR ALL : Reg16 USE ENTITY ece411.Reg16;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'High' of 'constval'
   WRITE_L <= '1';

   -- ModuleWare code(v1.9) for instance 'U_1' of 'constval'
   dout <= '1';

   -- Instance port mappings.
   mIcacheController : Cache_Controller
      PORT MAP (
         DirtyOut   => DirtyOut,
         MREAD_L    => I_MREAD_L,
         MWRITEL_L  => WRITE_L,
         PMRESP_H   => I_PMRESP_H,
         RESET_L    => RESET_L,
         clk        => CLK,
         hit        => hit,
         CacheWrite => CacheWrite,
         Evict_H    => Evict_H,
         MissCount  => MissCount,
         PMREAD_L   => I_MREAD_pm_L,
         PMWRITE_L  => OPEN
      );
   mIcacheDatapath : Cache_Datapath
      PORT MAP (
         ADDRESS    => I_ADDRESS,
         CacheWrite => CacheWrite,
         DATAOUT    => I_ADDRESS,
         Evict_H    => Evict_H,
         MREAD_L    => I_MREAD_L,
         MWRITEH_L  => WRITE_L,
         MWRITEL_L  => WRITE_L,
         PMDATAIN   => I_PMDATAIN,
         RESET_L    => RESET_L,
         clk        => CLK,
         DATAIN     => I_DATAIN,
         DirtyOut   => DirtyOut,
         LRUOut     => OPEN,
         MRESP_H    => I_MRESP_H,
         PMADDRESS  => I_ADDRESS_pm,
         PMDATAOUT  => OPEN,
         hit        => hit
      );
   U_2 : Plus1
      PORT MAP (
         CLK     => CLK,
         DataIn  => IMissCount,
         DataOut => IMissPlus1
      );
   IMissCounter : Reg16
      PORT MAP (
         Input  => IMissPlus1,
         RESET  => RESET_L,
         clk    => MissCount,
         load   => dout,
         Output => IMissCount
      );

END struct;
