-- VHDL Entity ece411.ID_ControlSplit.generatedInstance
--
-- Created:
--          by - baker30.ews (gelib-057-15.ews.illinois.edu)
--          at - 03:11:57 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ID_ControlSplit IS
   PORT( 
      CLK             : IN     STD_LOGIC;
      DRMUXSel        : OUT    std_logic;
      id_controls_out : IN     CONTROL_WORD;
      IDPCMUXSel      : OUT    std_logic;
      PCAddMUXSel     : OUT    std_logic;
      SRAMUXSel       : OUT    std_logic
   );

END ID_ControlSplit ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ID_ControlSplit IS 
BEGIN


END generatedInstance;
