-- VHDL Entity ece411.IR2Dr.generatedInstance
--
-- Created:
--          by - baker30.ews (gelib-057-15.ews.illinois.edu)
--          at - 03:11:59 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY IR2Dr IS
   PORT( 
      CLK      : IN     STD_LOGIC;
      wb_DR    : OUT    LC3B_REG;
      wb_IR_in : IN     LC3B_WORD
   );

END IR2Dr ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF IR2Dr IS 
BEGIN


END generatedInstance;
