-- VHDL Entity ece411.IR_SPlit.generatedInstance
--
-- Created:
--          by - baker30.ews (dcl-l440-22.ews.illinois.edu)
--          at - 14:37:32 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY IR_SPlit IS
   PORT( 
      CLK      : IN     STD_LOGIC;
      DR       : OUT    lc3b_reg;
      id_IR_in : IN     LC3B_WORD;
      imm5     : OUT    lc3b_imm5;
      off11    : OUT    lc3b_offset11;
      off6     : OUT    lc3b_offset6;
      off9     : OUT    lc3b_offset9;
      OpCode   : OUT    lc3b_opcode;
      SR1_BR   : OUT    lc3b_reg;
      SR2      : OUT    lc3b_reg;
      trap8    : OUT    lc3b_trapvect8
   );

END IR_SPlit ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF IR_SPlit IS 
BEGIN


END generatedInstance;
