-- VHDL Entity ece411.IReadDelay.generatedInstance
--
-- Created:
--          by - baker30.ews (gelib-057-15.ews.illinois.edu)
--          at - 03:11:58 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY IReadDelay IS
   PORT( 
      CLK       : IN     STD_LOGIC;
      I_MREAD_L : OUT    STD_LOGIC
   );

END IReadDelay ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF IReadDelay IS 
BEGIN


END generatedInstance;
