-- VHDL Entity ece411.LRU.generatedInstance
--
-- Created:
--          by - baker30.ews (gelib-057-01.ews.illinois.edu)
--          at - 15:17:11 04/20/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY LRU IS
   PORT( 
      CLK       : IN     std_logic;
      EncodeHit : IN     LC3B_8MUX_SEL;
      hit       : IN     std_logic;
      Index     : IN     LC3B_C_INDEX;
      LRUout    : OUT    LC3B_8MUX_SEL;
      MREAD_L   : IN     std_logic;
      MWRITE_L  : IN     std_logic;
      RESET_L   : IN     std_logic
   );

END LRU ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF LRU IS 
BEGIN


END generatedInstance;
