-- VHDL Entity ece411.NZP_COMB.generatedInstance
--
-- Created:
--          by - baker30.ews (dcl-l440-22.ews.illinois.edu)
--          at - 14:37:31 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY NZP_COMB IS
   PORT( 
      CLK        : IN     STD_LOGIC;
      ex_nzp_out : OUT    LC3B_CC;
      n          : IN     std_logic;
      p          : IN     std_logic;
      z          : IN     std_logic
   );

END NZP_COMB ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF NZP_COMB IS 
BEGIN


END generatedInstance;
