-- VHDL Entity ece411.PCAdder.generatedInstance
--
-- Created:
--          by - baker30.ews (dcl-l440-22.ews.illinois.edu)
--          at - 14:37:32 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY PCAdder IS
   PORT( 
      CLK         : IN     STD_LOGIC;
      id_PC_in    : IN     LC3B_WORD;
      PCADDMuxOUT : IN     LC3b_word;
      PCPlus      : OUT    LC3b_word
   );

END PCAdder ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF PCAdder IS 
BEGIN


END generatedInstance;
