-- VHDL Entity ece411.ResetDelay.generatedInstance
--
-- Created:
--          by - baker30.ews (gelib-057-04.ews.illinois.edu)
--          at - 23:26:28 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ResetDelay IS
   PORT( 
      CLK           : IN     STD_LOGIC;
      RESET_DELAYED : OUT    std_logic;
      RESET_L       : IN     STD_LOGIC
   );

END ResetDelay ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ResetDelay IS 
BEGIN


END generatedInstance;
