-- VHDL Entity ece411.resetDel.generatedInstance
--
-- Created:
--          by - baker30.ews (gelib-057-04.ews.illinois.edu)
--          at - 23:26:27 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY resetDel IS
   PORT( 
      CLK      : IN     STD_LOGIC;
      RESET_L  : IN     STD_LOGIC;
      RESET_L1 : OUT    STD_LOGIC
   );

END resetDel ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF resetDel IS 
BEGIN


END generatedInstance;
