-- VHDL Entity ece411.ValidBits.interface
--
-- Created:
--          by - baker30.ews (gelib-057-01.ews.illinois.edu)
--          at - 16:37:48 04/20/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ValidBits IS
   PORT( 
      DataWrite0 : IN     std_logic;
      DataWrite1 : IN     std_logic;
      DataWrite2 : IN     std_logic;
      DataWrite3 : IN     std_logic;
      DataWrite4 : IN     std_logic;
      DataWrite5 : IN     std_logic;
      DataWrite6 : IN     std_logic;
      DataWrite7 : IN     std_logic;
      Index      : IN     LC3B_C_INDEX;
      RESET_L    : IN     std_logic;
      VBitOut0   : OUT    std_logic;
      VBitOut1   : OUT    std_logic;
      VBitOut2   : OUT    std_logic;
      VBitOut3   : OUT    std_logic;
      VBitOut4   : OUT    std_logic;
      VBitOut5   : OUT    std_logic;
      VBitOut6   : OUT    std_logic;
      VBitOut7   : OUT    std_logic
   );

-- Declarations

END ValidBits ;

--
-- VHDL Architecture ece411.ValidBits.struct
--
-- Created:
--          by - baker30.ews (gelib-057-01.ews.illinois.edu)
--          at - 16:37:48 04/20/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF ValidBits IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL HighConst : std_logic;


   -- Component Declarations
   COMPONENT BitArray
   PORT (
      BitIn    : IN     std_logic;
      BitWrite : IN     std_logic;
      Index    : IN     LC3B_C_INDEX;
      Reset_L  : IN     std_logic;
      BitOut   : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : BitArray USE ENTITY ece411.BitArray;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'Const1' of 'constval'
   HighConst <= '1';

   -- Instance port mappings.
   validBit0 : BitArray
      PORT MAP (
         Reset_L  => RESET_L,
         BitWrite => DataWrite0,
         Index    => Index,
         BitIn    => HighConst,
         BitOut   => VBitOut0
      );
   validBit1 : BitArray
      PORT MAP (
         Reset_L  => RESET_L,
         BitWrite => DataWrite1,
         Index    => Index,
         BitIn    => HighConst,
         BitOut   => VBitOut1
      );
   validBit2 : BitArray
      PORT MAP (
         Reset_L  => RESET_L,
         BitWrite => DataWrite2,
         Index    => Index,
         BitIn    => HighConst,
         BitOut   => VBitOut2
      );
   validBit3 : BitArray
      PORT MAP (
         Reset_L  => RESET_L,
         BitWrite => DataWrite3,
         Index    => Index,
         BitIn    => HighConst,
         BitOut   => VBitOut3
      );
   validBit4 : BitArray
      PORT MAP (
         Reset_L  => RESET_L,
         BitWrite => DataWrite4,
         Index    => Index,
         BitIn    => HighConst,
         BitOut   => VBitOut4
      );
   validBit5 : BitArray
      PORT MAP (
         Reset_L  => RESET_L,
         BitWrite => DataWrite5,
         Index    => Index,
         BitIn    => HighConst,
         BitOut   => VBitOut5
      );
   validBit6 : BitArray
      PORT MAP (
         Reset_L  => RESET_L,
         BitWrite => DataWrite6,
         Index    => Index,
         BitIn    => HighConst,
         BitOut   => VBitOut6
      );
   validBit7 : BitArray
      PORT MAP (
         Reset_L  => RESET_L,
         BitWrite => DataWrite7,
         Index    => Index,
         BitIn    => HighConst,
         BitOut   => VBitOut7
      );

END struct;
