-- VHDL Entity ece411.WB_CntrlStrip.generatedInstance
--
-- Created:
--          by - baker30.ews (gelib-057-15.ews.illinois.edu)
--          at - 03:11:59 03/13/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY WB_CntrlStrip IS
   PORT( 
      ByteMUXSel     : OUT    std_logic;
      CLK            : IN     STD_LOGIC;
      RegDataMuxSel  : OUT    LC3B_4MUXSEL;
      wb_controls_in : IN     CONTROL_WORD;
      wb_regWrite    : OUT    std_logic
   );

END WB_CntrlStrip ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF WB_CntrlStrip IS 
BEGIN


END generatedInstance;
