-- VHDL Entity ece411.WordDataSel.symbol
--
-- Created:
--          by - baker30.ews (evrt-252-27.ews.illinois.edu)
--          at - 17:49:09 03/03/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;
USE ieee.std_logic_arith.all;

ENTITY WordDataSel IS
   PORT( 
      Dec       : IN     std_logic;
      MWriteH_L : IN     std_logic;
      NewByteH  : IN     LC3B_BYTE;
      NewByteL  : IN     LC3B_BYTE;
      Offset0   : IN     std_logic;
      OldByteH  : IN     LC3B_BYTE;
      OldByteL  : IN     LC3B_BYTE;
      OutWord   : OUT    LC3B_WORD
   );

-- Declarations

END WordDataSel ;

--
-- VHDL Architecture ece411.WordDataSel.struct
--
-- Created:
--          by - baker30.ews (evrt-252-27.ews.illinois.edu)
--          at - 17:49:09 03/03/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF WordDataSel IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL ByteHigh : LC3B_BYTE;
   SIGNAL ByteLow  : LC3B_BYTE;
   SIGNAL F        : std_logic;
   SIGNAL F1       : std_logic;
   SIGNAL F2       : std_logic;
   SIGNAL F3       : std_logic;
   SIGNAL F4       : std_logic;


   -- Component Declarations
   COMPONENT AND2
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      F : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT ByteMux2
   PORT (
      A   : IN     LC3B_BYTE;
      B   : IN     LC3B_BYTE;
      Sel : IN     std_logic;
      F   : OUT    LC3B_BYTE
   );
   END COMPONENT;
   COMPONENT Bytes2Word
   PORT (
      ByteHigh : IN     LC3B_BYTE;
      ByteLow  : IN     LC3B_BYTE;
      OutWord  : OUT    LC3B_WORD
   );
   END COMPONENT;
   COMPONENT NOT2
   PORT (
      A : IN     std_logic;
      F : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT OR2
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      F : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2 USE ENTITY ece411.AND2;
   FOR ALL : ByteMux2 USE ENTITY ece411.ByteMux2;
   FOR ALL : Bytes2Word USE ENTITY ece411.Bytes2Word;
   FOR ALL : NOT2 USE ENTITY ece411.NOT2;
   FOR ALL : OR2 USE ENTITY ece411.OR2;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_2 : AND2
      PORT MAP (
         A => Dec,
         B => F,
         F => F4
      );
   U_3 : AND2
      PORT MAP (
         A => Dec,
         B => F1,
         F => F2
      );
   ByteH : ByteMux2
      PORT MAP (
         Sel => F4,
         A   => OldByteH,
         B   => NewByteH,
         F   => ByteHigh
      );
   ByteL : ByteMux2
      PORT MAP (
         Sel => F2,
         A   => OldByteL,
         B   => NewByteL,
         F   => ByteLow
      );
   U_5 : Bytes2Word
      PORT MAP (
         ByteLow  => ByteLow,
         ByteHigh => ByteHigh,
         OutWord  => OutWord
      );
   U_0 : NOT2
      PORT MAP (
         A => MWriteH_L,
         F => F3
      );
   U_1 : NOT2
      PORT MAP (
         A => Offset0,
         F => F1
      );
   U_4 : OR2
      PORT MAP (
         A => Offset0,
         B => F3,
         F => F
      );

END struct;
